SHOW DATABASES;
USE your_database_name;
SHOW TABLES;
DESCRIBE Users;
DESCRIBE Events;
DESCRIBE Sessions;
DESCRIBE Registrations;
DESCRIBE Feedback;
DESCRIBE Resources;
SELECT * FROM Users;
SELECT * FROM Events;
SELECT * FROM Sessions;
SELECT * FROM Registrations;
SELECT * FROM Feedback;
SELECT * FROM Resources;
